repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v1.0.0
  hooks:
  - id: dbt-docs-generate
    args: ["--cmd-flags", "++profiles-dir", "./"]
  - id: check-model-has-tests
    name: Check that all models have tests
    files: ^models/
